name: sih
description: Project for Six Muskeeters AirCare

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  line_icons: ^0.2.0
  geolocator: ^5.3.1
  font_awesome_flutter: ^8.8.1
  flutter:
    sdk: flutter
  google_nav_bar: ^2.2.0
  introduction_screen: ^1.0.8
  md2_tab_indicator: ^1.0.2
  wifi_iot: ^0.1.1
  lottie: ^0.4.1
  random_string: ^2.1.0
  flutter_dialogflow: ^0.1.3
  cloud_firestore: ^0.13.4+2
  mapwize: ^0.0.1-beta.4
  wifi_hunter: ^1.0.3
  android_wifi_info: ^0.1.1
  provider: ^3.1.0+1
  google_maps_flutter: ^0.5.21+8

  google_maps_webservice: ^0.0.14
  pin_code_text_field: ^1.4.0
  shared_preferences: ^0.5.4
  sliding_up_panel: ^0.3.6
  carousel_slider: ^1.3.0
  connectivity: ^0.4.5+2
  flutter_spinkit: ^4.0.0
  google_fonts:
  flutter_speed_dial: ^1.2.5
  webview_flutter:
  firebase_auth: ^0.15.4
  pin_entry_text_field: ^0.1.4
  android_intent: ^0.3.6+12
  permission_handler: ^4.4.0+hotfix.2
  qr_flutter: ^1.1.1
  toast: ^0.1.5
  url_launcher: ^5.4.11
  flutter_swiper:
  flutter_svg:
  path_provider: ^1.4.0
  barcode_scan: ^3.0.1
  clipboard: ^0.1.2+8
  wifi_flutter: ^0.1.0+1
  store_redirect:
  google_sign_in:
  pin_code_fields: ^4.0.0
  flutter_verification_code: ^0.2.0
  flutter_rating_bar: ^3.0.1+1
  qrscan: ^0.2.17
  flutter_qr_reader: ^1.0.3
  image_picker:
  majascan: ^0.3.7
  flutter_bloc:
  bloc:
  equatable: ^1.0.3
  shimmer:
  smooth_star_rating:
  http: ^0.12.0+2
  intl: ^0.15.8
  charts_flutter: ^0.6.0
  english_words: ^3.1.3
  location:
  rate_my_app: ^0.6.1+6
  rate_app_dialog: ^0.1.2
  datetime_picker_formfield: ^1.0.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/food.png
    - assets/
    - assets/waiting-room.png
    - assets/company.png
    - assets/shop.png
    - assets/gps-navigation.png
    - assets/parking.png
    - assets/customer-support.png
    - assets/lighthouse.png
    - assets/wireless-router.png
    - assets/hotel.png
    - assets/wheelchair.png
    - assets/baggage.png
    - assets/flight.png
    - assets/passenger.png
    - assets/passengerswait.png
    - assets/tickets.png
    - assets/water-bottle.png
    - assets/telemarketer.png
    - assets/hand-wash.png
    - assets/433-checked-done.json
    - assets/23749-successful.json
    - assets/6936-class-ninjas-floating-ninja.json
    - assets/12821-failed-attempt.json
    - assets/21332-teamwork.json
    - assets/lifebuoy.png
    - assets/tele.png
    - assets/mail.png
    - assets/percent.png
    - assets/icons8-help-64.png
    - assets/icons8-email-64.png
    - assets/icons8-call-64.png
    - assets/icons8-chat-bubble-64.png
    - assets/pointer.json
    - assets/lf30_editor_zzpgEe.json
    - assets/lf30_editor_muUzxw.json
    - assets/bg.jpg
    - assets/8014-joyful-background.json
    - assets/animation_500_kcre1tf4.gif
    - assets/credentials.json
    - assets/men.png
    - assets/3603-chat-animation.json
    - assets/ic_launcher.png
    - assets/euro.png
    - assets/location.png
    - assets/tourism.png
    - assets/car.png
    - assets/gift.png
    - assets/qr_ticket.png
    - assets/qr-code.png
    - assets/cm1.jpeg
    - assets/cm2.jpeg
    - assets/cm3.jpeg
    - assets/cm4.jpeg
    - assets/food1.jpeg
    - assets/food2.jpeg
    - assets/food3.jpeg
    - assets/food4.jpeg
    - assets/food5.jpeg
    - assets/food6.jpeg
    - assets/food7.jpeg
    - assets/food8.jpeg
    - assets/food9.jpeg
    - assets/food10.jpeg
    - assets/food11.jpeg
    - assets/food12.jpg
    - assets/tour-pic.jpg
    - assets/tour-pic-plan.jpg
    - assets/lf30_editor_1tlcZH.json
    - assets/0.jpg
    - assets/1.jpg
    - assets/2.jpg
    - assets/12363-heart.json
    - assets/5.jpg
    - assets/6.jfif
    - assets/8.jfif
    - assets/ticket_section.png
    - assets/bell.png
    - assets/bed.png
    - assets/taxier.png
    - assets/shops.png
    - assets/bed-1.png
    - assets/wheelchairs.png
    - assets/router.png
    - assets/claims.png
    - assets/notepad.png
    - assets/support.png
    - assets/discount.png
    - assets/money.png
    - assets/parkings.png
    - assets/time.png
    - assets/water.png
    - assets/airport.png
    - assets/pilot.png
    - assets/countrycodes.json
    - assets/animation_500_kd1hfn8v.gif
    - assets/animation_500_kd1hhr4l.gif
    - assets/lf30_editor_0nC6US.json
    - assets/lf30_editor_OJeMpc.json
    - assets/images/
    - assets/icons/
    - images/




  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MavenPro
      fonts:
        - asset: lib2/MavenPro-Regular.ttf
        - asset: lib2/MavenPro-Black.ttf
        - asset: lib2/MavenPro-Bold.ttf
        - asset: lib2/MavenPro-SemiBold.ttf
        - asset: lib2/MavenPro-Medium.ttf
        - asset: lib2/MavenPro-ExtraBold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
